version: '3.8'
services:
  chat_client:
    build:
      context: ./src/chat_client
    container_name: chat_client
    ports:
      - "3000:3000"
    depends_on:
      - super_agent_server
    env_file:
      - .env
    volumes:
      - ./config/chat_client.json:/usr/share/nginx/html/chat_client.json:ro
  super_agent_server:
    build:
      context: ./src/super_agent_server
    container_name: super_agent_server
    ports:
      - "5001:5001"
    volumes:
      - ./src/super_agent_server:/app
    depends_on:
      - agent_registry_service
      - linux_metrics_ai_agent
      - linux_command_ai_agent
    env_file:
      - .env
  agent_registry_service:
    build:
      context: ./src/agent_registry_service
    container_name: agent_registry_service
    ports:
      - "5002:5002"
    volumes:
      - ./src/agent_registry_service:/app
    env_file:
      - .env
  linux_metrics_ai_agent:
    build:
      context: ./src/linux_metrics_ai_agent
    container_name: linux_metrics_ai_agent
    ports:
      - "5003:5000"
    environment:
      - AGENT_ENDPOINT=http://linux_metrics_ai_agent:5000
    env_file:
      - .env
  linux_command_ai_agent:
    build:
      context: ./src/linux_command_ai_agent
      dockerfile: Dockerfile
    container_name: linux_command_ai_agent
    ports:
      - "5004:5000"
    environment:
      - AGENT_ENDPOINT=http://linux_command_ai_agent:5000
    env_file:
      - .env
